const Credentials = [
  {
    userName: "Jhon",
    password: "Aa123456",
    userId: "11",
    authorization: "authorizedUser",
    accessToken:
      '{"secret":"59e42351-c6f2-4539-99c4-a866999380b7","expirationDate":"2023-09-21T06:21:08.295Z"}',
  },
  {
    userName: "JhonTravolta",
    password: "Aa123456",
    userId: "111",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Lisa",
    password: "Aa123456",
    userId: "12",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "JonathanTheKing",
    password: "Aa123456",
    userId: "13",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Jonathan",
    password: "Aa123456",
    userId: "ed832cad-3fdd-479e-8e82-35f02d78ef0a",
    authorization: "admin",
    accessToken: {
      secret: "a121ff4e-4ab6-4e39-8e7a-2f4f5b322741",
      expirationDate: "2023-09-21T06:20:48.310Z",
    },
  },
  {
    userName: "Alice",
    password: "Bb987654",
    userId: "21",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Bob",
    password: "Cc543210",
    userId: "22",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Charlie",
    password: "Dd456789",
    userId: "23",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "David",
    password: "Ee987654",
    userId: "24",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Eve",
    password: "Ff123456",
    userId: "25",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Frank",
    password: "Gg987654",
    userId: "26",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Grace",
    password: "Hh543210",
    userId: "27",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Henry",
    password: "Ii456789",
    userId: "28",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Isabel",
    password: "Jj987654",
    userId: "29",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Jack",
    password: "Kk123456",
    userId: "30",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Kate",
    password: "Ll987654",
    userId: "31",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Liam",
    password: "Mm543210",
    userId: "32",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Mia",
    password: "Nn456789",
    userId: "33",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Noah",
    password: "Oo987654",
    userId: "34",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Olivia",
    password: "Pp123456",
    userId: "35",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "William",
    password: "Qq987654",
    userId: "36",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Sophia",
    password: "Rr543210",
    userId: "37",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "James",
    password: "Ss456789",
    userId: "38",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Emma",
    password: "Tt987654",
    userId: "39",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
  {
    userName: "Benjamin",
    password: "Uu123456",
    userId: "40",
    authorization: "authorizedUser",
    accessToken: { secret: "", expirationDate: "" },
  },
];
module.exports = { Credentials };
