const Users = [
  {
    userId: "1",
    userName: "Test",
    profileImage: "/images/default-profile-image.png",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "11",
    userName: "Jhon",
    profileImage: "/images/Jhon.jpg",
    posts: ["11", "12", "13"],
    following: ["Jhon", "JhonTravolta", "Jonathan", "JonathanTheKing"],
    highScore: "100",
  },
  {
    userId: "111",
    userName: "JhonTravolta",
    profileImage: "/images/Jhon.jpg",
    posts: ["11", "12", "13"],
    following: ["Jhon", "Lisa", "Jonathan"],
    highScore: "250",
  },
  {
    userId: "12",
    userName: "Lisa",
    profileImage: "/images/Lisa.jpg",
    posts: ["11", "12", "13"],
    following: [],
    highScore: "303",
  },
  {
    userId: "13",
    userName: "JonathanTheKing",
    profileImage: "/images/Jonathan.jpg",
    posts: ["11", "12", "13"],
    following: ["JhonTravolta", "Lisa"],
    highScore: "401",
  },
  {
    userId: "ed832cad-3fdd-479e-8e82-35f02d78ef0a",
    userName: "Jonathan",
    profileImage: "/images/Jonathan.jpg",
    posts: ["11", "12", "13"],
    following: ["JhonTravolta", "Jhon"],
    highScore: "500",
  },
  {
    userId: "21",
    userName: "Alice",
    profileImage: "/images/Alice.jpg",
    posts: [],
    following: [],
    highScore: "707",
  },
  {
    userId: "22",
    userName: "Bob",
    profileImage: "/images/Bob.jpg",
    posts: [],
    following: [],
    highScore: "640",
  },
  {
    userId: "23",
    userName: "Charlie",
    profileImage: "/images/Charlie.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "24",
    userName: "David",
    profileImage: "/images/David.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "25",
    userName: "Eve",
    profileImage: "/images/Eve.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "26",
    userName: "Frank",
    profileImage: "/images/Frank.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "27",
    userName: "Grace",
    profileImage: "/images/Grace.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "28",
    userName: "Henry",
    profileImage: "/images/Henry.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "29",
    userName: "Isabel",
    profileImage: "/images/Isabel.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "30",
    userName: "Jack",
    profileImage: "/images/Jack.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "31",
    userName: "Kate",
    profileImage: "/images/Kate.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "32",
    userName: "Liam",
    profileImage: "/images/Liam.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "33",
    userName: "Mia",
    profileImage: "/images/Mia.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "34",
    userName: "Noah",
    profileImage: "/images/Noah.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "35",
    userName: "Olivia",
    profileImage: "/images/Olivia.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "36",
    userName: "William",
    profileImage: "/images/William.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "37",
    userName: "Sophia",
    profileImage: "/images/Sophia.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "38",
    userName: "James",
    profileImage: "/images/James.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "39",
    userName: "Emma",
    profileImage: "/images/Emma.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "40",
    userName: "Benjamin",
    profileImage: "/images/Benjamin.jpg",
    posts: [],
    following: [],
    highScore: "0",
  },
  {
    userId: "22feb387-2fe5-43d1-ad05-06daf387764f",
    userName: "Bar",
    profileImage: "/images/default-profile-image.png",
    posts: [],
    following: ["JhonTravolta", "Lisa", "JonathanTheKing", "Alice"],
    highScore: 0,
  },
];
module.exports = { Users };
